[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "boba-app"
version = "0.1.0"
description = "Boba application — use cases, tools, pipelines"
authors = ["Sergei Solomatov"]
packages = [{ include = "boba_app", from = "src" }]

[tool.poetry.dependencies]
python = "^3.11"
boba-domain = { path = "../boba-domain", develop = true }
langchain-core = "*"
