[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "boba-chainlit"
version = "0.1.0"
description = "Boba Chainlit UI"
authors = ["Sergei Solomatov"]
packages = [{ include = "boba/chainlit", from = "src" }]

[tool.poetry.dependencies]
python = "^3.11"
boba-infra = { path = "../infra", develop = true }
chainlit = "*"
