services:
  studio:
    init: true
    cgroup_parent: boba-studio.slice
    user: "${BOBA_USER}"
    devices:
      - /dev/fuse
    security_opt:
      - seccomp=../../build/conf/seccomp-sandbox.json
      - systempaths=unconfined
      - no-new-privileges:true
    cap_drop:
      - ALL
    mem_limit: 16g
    cpus: 8
    pids_limit: 2048
    restart: unless-stopped
    image: boba-studio:0.0.26.dev4
    hostname: studio
    container_name: studio
    networks:
      default:
        ipv4_address: ${BOBA_ADDRESS}
    env_file: ./conf/boba.env
    command:
      - -m
      - boba.studio
      - --config
      - /app/boba/conf/config.toml
      - --site
      - /app/boba/conf/site.toml
    volumes:
      - ./conf/site.toml:/app/boba/conf/site.toml:ro
      - ./conf/krb:/app/boba/conf/krb:ro
      - ./conf/krb/krb5.conf:/etc/krb5.conf:ro
      - ./data:/app/boba/data:rw
      - ./app_root:/app/boba/app_root:rw
      - ../../runtime/models:/app/boba/models:ro
      - ../../runtime/sandbox:/app/boba/sandbox:ro
      - ${BOBA_SANDBOX_CGROUP}:/cgroup/boba-sandbox-studio:rw
    ports:
      - "8502"

networks:
  default:
    name: ${BOBA_NETWORK}
    external: ${BOBA_NETWORK_EXTERNAL}
