"""Домен workflow: спека, граф стадий, автомат запуска. Без I/O."""

from boba.workflow.events import RunSnapshot
from boba.workflow.graph import (
    ArgBinding,
    RunState,
    RunStatus,
    Stage,
    TaskState,
    TaskStatus,
    ToolArg,
    ToolCatalog,
    ToolFacts,
    ToolPort,
    WorkflowGraph,
    WorkflowPlan,
    WorkflowPlanError,
)
from boba.workflow.ports import RunSink, WorkflowRepository
from boba.workflow.records import (
    DraftKey,
    DraftKind,
    RunOutcome,
    StopOutcome,
    StoredRun,
    StoredWorkflow,
    TaskOutcome,
    WorkflowDraft,
    WorkflowError,
    WorkflowNotFoundError,
    WorkflowRefusal,
    WorkflowRunError,
    WorkflowStoreError,
)
from boba.workflow.spec import (
    ArgTemplate,
    Edge,
    EdgeKind,
    EdgeText,
    IssueCode,
    PortDirection,
    PortKind,
    PortRef,
    SpecIssue,
    TaskSpec,
    WorkflowSpec,
    WorkflowSpecError,
)

__all__ = [
    "ArgBinding",
    "ArgTemplate",
    "DraftKey",
    "DraftKind",
    "Edge",
    "EdgeKind",
    "EdgeText",
    "IssueCode",
    "PortDirection",
    "PortKind",
    "PortRef",
    "RunOutcome",
    "RunSink",
    "RunSnapshot",
    "RunState",
    "RunStatus",
    "SpecIssue",
    "Stage",
    "StopOutcome",
    "StoredRun",
    "StoredWorkflow",
    "TaskOutcome",
    "TaskSpec",
    "TaskState",
    "TaskStatus",
    "ToolArg",
    "ToolCatalog",
    "ToolFacts",
    "ToolPort",
    "WorkflowDraft",
    "WorkflowError",
    "WorkflowGraph",
    "WorkflowNotFoundError",
    "WorkflowPlan",
    "WorkflowPlanError",
    "WorkflowRefusal",
    "WorkflowRepository",
    "WorkflowRunError",
    "WorkflowSpec",
    "WorkflowSpecError",
    "WorkflowStoreError",
]
