set pages 0 feedback off
grant select on sys.user$ to boba_svc;
grant select on sys.obj$ to boba_svc;
grant select on sys.tab$ to boba_svc;
grant select on sys.col$ to boba_svc;
grant select on sys.com$ to boba_svc;
grant select on sys.con$ to boba_svc;
grant select on sys.cdef$ to boba_svc;
grant select on sys.ccol$ to boba_svc;
grant select on sys.ind$ to boba_svc;
grant select on sys.icol$ to boba_svc;
grant select on sys.view$ to boba_svc;
grant select on sys.snap$ to boba_svc;
grant select on sys.seq$ to boba_svc;
grant select on sys.syn$ to boba_svc;
grant select on sys.trigger$ to boba_svc;
grant select on sys.dependency$ to boba_svc;
grant select on sys.partobj$ to boba_svc;
grant select on sys.partcol$ to boba_svc;
grant select on sys.ts$ to boba_svc;
grant select on sys.registry$ to boba_svc;
grant select on sys.props$ to boba_svc;
select 'granted ' || count(*) from dba_tab_privs where grantee = 'BOBA_SVC';
