@host = https://loshara.com/boba
@hostDebug = https://loshara.com/boba-debug

### Health (docker)
GET {{host}}/health

### Health (debug/launch.json)
GET {{hostDebug}}/health

### Chat (docker)
POST {{host}}/api/chat
Content-Type: application/json

{
  "folder": "PAAS-2",
  "message": "как именовать таблицы в adqm?"
}

### Chat (debug/launch.json)
POST {{hostDebug}}/api/chat
Content-Type: application/json

{
  "folder": "PAAS-2",
  "message": "как именовать таблицы в adqm?"
}

### Chat с выбором модели
POST {{host}}/api/chat
Content-Type: application/json

{
  "folder": "PAAS-2",
  "message": "привет",
  "model": "qwen3"
}
