services:
  n1bot:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: n1bot
    volumes:
      - ./chroma_app_db:/app/chroma_app_db
    env_file:
      - env/.env.testing
    restart: always
    networks:
      - default

networks:
  default:
    name: docker
    external: true
