"""Публичный API core-слоя.

Реэкспортирует базовые доменные примитивы: иерархию маршрутизируемых
ошибок, паттерны потоков/конвертеров, доменные модели tools и workspace.

Импорты короткой формой::

    from boba.domain.core import Converter, StreamSource, Specification
    from boba.domain.core import RoutableError, TerminalError, UserNoticeError
"""

from boba.domain.core.errors import (
    LLMFeedbackError,
    Retryable,
    RoutableError,
    TerminalError,
    UserFeedbackError,
    UserNoticeError,
    UserNoticeSeverity,
)
from boba.domain.core.patterns import (
    AllMatchesDispatcher,
    ContextFactoryMethod,
    Converter,
    ConverterError,
    ConverterInputError,
    ConverterOutputError,
    Definition,
    ExceptionSpecification,
    Executor,
    FactoryMethod,
    FirstMatchConverter,
    FirstMatchDispatcher,
    FoldFactory,
    FoldingDispatcher,
    Id,
    IsInstance,
    Matcher,
    PrioritySource,
    Resolver,
    Serializer,
    Specification,
    StateFull,
    StateLess,
    StreamConverter,
    StreamSink,
    StreamSinkPipeline,
    StreamSource,
    StreamSourceChainBuilder,
    StreamSourceLoop,
    StreamSourcePipeline,
    StreamTransformer,
    StreamTransformerPipeline,
    UuId,
    Validator,
)
from boba.domain.core.tools import (
    JsonType,
    ParamSchema,
    Tool,
    ToolCall,
    ToolCatalog,
    ToolDefinition,
    ToolExecutionError,
    ToolFactory,
    ToolId,
    ToolIdCollisionError,
    ToolInputSchema,
    ToolResult,
    ToolsService,
    ToolSource,
    ToolSourceId,
    ToolStore,
)
from boba.domain.core.workspace import (
    FileMeta,
    WorkspaceDecodingError,
    WorkspaceError,
    WorkspaceId,
    WorkspaceManager,
    WorkspaceNotFoundError,
    WorkspacePermissionError,
    WorkspaceService,
)

__all__ = [
    "AllMatchesDispatcher",
    "ContextFactoryMethod",
    "Converter",
    "ConverterError",
    "ConverterInputError",
    "ConverterOutputError",
    "Definition",
    "ExceptionSpecification",
    "Executor",
    "FactoryMethod",
    "FileMeta",
    "FirstMatchConverter",
    "FirstMatchDispatcher",
    "FoldFactory",
    "FoldingDispatcher",
    "Id",
    "IsInstance",
    "JsonType",
    "LLMFeedbackError",
    "Matcher",
    "ParamSchema",
    "PrioritySource",
    "Resolver",
    "Retryable",
    "RoutableError",
    "Serializer",
    "Specification",
    "StateFull",
    "StateLess",
    "StreamConverter",
    "StreamSink",
    "StreamSinkPipeline",
    "StreamSource",
    "StreamSourceChainBuilder",
    "StreamSourceLoop",
    "StreamSourcePipeline",
    "StreamTransformer",
    "StreamTransformerPipeline",
    "TerminalError",
    "Tool",
    "ToolCall",
    "ToolCatalog",
    "ToolDefinition",
    "ToolExecutionError",
    "ToolFactory",
    "ToolId",
    "ToolIdCollisionError",
    "ToolInputSchema",
    "ToolResult",
    "ToolSource",
    "ToolSourceId",
    "ToolStore",
    "ToolsService",
    "UserFeedbackError",
    "UserNoticeError",
    "UserNoticeSeverity",
    "UuId",
    "Validator",
    "WorkspaceDecodingError",
    "WorkspaceError",
    "WorkspaceId",
    "WorkspaceManager",
    "WorkspaceNotFoundError",
    "WorkspacePermissionError",
    "WorkspaceService",
]
