create table edge_demo.customers (
    id          number(10) generated by default as identity primary key,
    email       varchar2(200) not null,
    full_name   nvarchar2(100),
    balance     number(18, 2) default 0 not null,
    created_at  timestamp(6) default systimestamp not null,
    notes       clob,
    status      char(1) default 'A',
    upper_mail  varchar2(200) generated always as (upper(email)) virtual,
    constraint customers_email_uk unique (email),
    constraint customers_status_ck check (status in ('A', 'B'))
)
/
comment on table edge_demo.customers is 'Клиенты'
/
comment on column edge_demo.customers.email is 'Почта, уникальна'
/
comment on column edge_demo.customers.balance is 'Баланс в рублях'
/
create index edge_demo.customers_name_ix on edge_demo.customers (lower(full_name))
/
create sequence edge_demo.customer_seq start with 1000 increment by 10 cache 50 nocycle
/
