[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "boba-app"
version = "0.1.0"
description = "Boba application — use cases, tools, pipelines"
authors = ["Sergei Solomatov"]
packages = [{ include = "boba/app", from = "src" }]

[tool.poetry.dependencies]
python = "^3.11"
boba-domain = { path = "../domain", develop = true }
boba-infra = { path = "../infra", develop = true }
