services:
  chainlit:
    image: boba:${BOBA_TAG}
    hostname: chainlit
    user: "${BOBA_UID:-1000}:${BOBA_GID:-984}"
    container_name: chainlit
    environment:
      - KRB5_CONFIG=/app/boba/conf/krb/krb5.conf
      - KRB5_CLIENT_KTNAME=/app/boba/conf/krb/boba-svc.keytab
      - KRB5CCNAME=FILE:/tmp/krb5cc
      - PGGSSENCMODE=prefer
    cgroup_parent: boba.slice
    volumes:
      - ./conf/config.toml:/app/boba/conf/config.toml:ro
      - ./conf/krb:/app/boba/conf/krb:ro
      - ./data:/app/boba/data:rw
      - /sys/fs/cgroup/boba.slice:/cgroup:rw
    devices:
      - /dev/fuse
    security_opt:
      - seccomp=unconfined
      - systempaths=unconfined
    ports:
      - 127.0.0.1:8503:8501
    restart: unless-stopped

networks:
  default:
    name: docker
    external: true
