"""Публичный API агент-слоя.

Реэкспортирует ошибки, события, сообщения, модели, prompt-примитивы и
middleware-цепочку (см. :mod:`boba.domain.agent.meat`).

Короткие импорты::

    from boba.domain.agent import Agent, AgentConfig, AgentContext
    from boba.domain.agent import AgentEvent, AnswerComplete, ToolResultReady
"""

from boba.domain.agent.dialogue_writer import DialogueWriter
from boba.domain.agent.errors import (
    LLMGenerationFailedError,
    LLMToolCallFormatError,
    MaxIterationsExceededError,
    RepeatedFormatFailureError,
)
from boba.domain.agent.events import (
    Advisory,
    AgentEvent,
    AgentEventName,
    AnswerComplete,
    AnswerStarted,
    AnswerToken,
    BaseAgentEvent,
    ContentDelta,
    ContentSnapshot,
    FeedbackToLLMAdded,
    GenerationDone,
    GenerationFailed,
    GenerationRetried,
    GenerationStarted,
    IterationStarted,
    LLMRequestSent,
    LLMResponseStreamOpened,
    MaxIterationsReached,
    PersistenceFailed,
    PhaseTransition,
    PromptFailed,
    RefusalComplete,
    RefusalToken,
    RepeatedFormatFailure,
    Severity,
    SlotKind,
    Terminal,
    ThinkingComplete,
    ThinkingStarted,
    ThinkingToken,
    ToolCallArgumentDelta,
    ToolCallComplete,
    ToolCallFormatFailed,
    ToolCallStreamStarted,
    ToolExecutionFailed,
    ToolExecutionStarted,
    ToolResultReady,
    UserQueryReceived,
)
from boba.domain.agent.meat import (
    Agent,
    AgentErrorRouter,
    AgentErrorRouterMiddleware,
    AssistantMessagePersistenceMiddleware,
    IterationCounterMiddleware,
    JsonContentToolCallMiddleware,
    JsonDepthScanner,
    JsonHeaderParser,
    JsonToolCallHeader,
    LLMInvokeMiddleware,
    ParsedJsonToolCall,
    RepeatedFormatFailureGuardMiddleware,
    RepeatedToolCallGuardMiddleware,
    StopOnAnyFailure,
    StopOnFinished,
    StrictJsonContentToolCallMiddleware,
    StrictJsonToolCallParser,
    ToolExecutionMiddleware,
)
from boba.domain.agent.messages import (
    MessageService,
    MessageStoreError,
    MessageStoreReadError,
    MessageStoreWriteError,
)
from boba.domain.agent.models import AgentConfig, AgentContext, AgentRequest
from boba.domain.agent.payloads import (
    ToolCallFailure,
    ToolCallFormatFailure,
    ToolCallResult,
)
from boba.domain.agent.prompt import (
    PermanentPromptError,
    PromptBlock,
    PromptError,
    PromptFactory,
    PromptId,
    PromptProvider,
    PromptProviderError,
    PromptResult,
    PromptState,
)
from boba.domain.agent.turn.reducers import (
    AgentRequestSamplingReducer,
    HistoryReducer,
    ModelReducer,
    SystemPromptReducer,
    ToolsReducer,
)
from boba.domain.agent.turn.spec import TurnResolveContext, TurnSpec, TurnState

__all__ = [
    "Advisory",
    "Agent",
    "AgentConfig",
    "AgentContext",
    "AgentErrorRouter",
    "AgentErrorRouterMiddleware",
    "AgentEvent",
    "AgentEventName",
    "AgentRequest",
    "AgentRequestSamplingReducer",
    "AnswerComplete",
    "AnswerStarted",
    "AnswerToken",
    "AssistantMessagePersistenceMiddleware",
    "BaseAgentEvent",
    "ContentDelta",
    "ContentSnapshot",
    "DialogueWriter",
    "FeedbackToLLMAdded",
    "GenerationDone",
    "GenerationFailed",
    "GenerationRetried",
    "GenerationStarted",
    "HistoryReducer",
    "IterationCounterMiddleware",
    "IterationStarted",
    "JsonContentToolCallMiddleware",
    "JsonDepthScanner",
    "JsonHeaderParser",
    "JsonToolCallHeader",
    "LLMGenerationFailedError",
    "LLMInvokeMiddleware",
    "LLMRequestSent",
    "LLMResponseStreamOpened",
    "LLMToolCallFormatError",
    "MaxIterationsExceededError",
    "MaxIterationsReached",
    "MessageService",
    "MessageStoreError",
    "MessageStoreReadError",
    "MessageStoreWriteError",
    "ModelReducer",
    "ParsedJsonToolCall",
    "PermanentPromptError",
    "PersistenceFailed",
    "PhaseTransition",
    "PromptBlock",
    "PromptError",
    "PromptFactory",
    "PromptFailed",
    "PromptId",
    "PromptProvider",
    "PromptProviderError",
    "PromptResult",
    "PromptState",
    "RefusalComplete",
    "RefusalToken",
    "RepeatedFormatFailure",
    "RepeatedFormatFailureError",
    "RepeatedFormatFailureGuardMiddleware",
    "RepeatedToolCallGuardMiddleware",
    "Severity",
    "SlotKind",
    "StopOnAnyFailure",
    "StopOnFinished",
    "StrictJsonContentToolCallMiddleware",
    "StrictJsonToolCallParser",
    "SystemPromptReducer",
    "Terminal",
    "ThinkingComplete",
    "ThinkingStarted",
    "ThinkingToken",
    "ToolCallArgumentDelta",
    "ToolCallComplete",
    "ToolCallFailure",
    "ToolCallFormatFailed",
    "ToolCallFormatFailure",
    "ToolCallResult",
    "ToolCallStreamStarted",
    "ToolExecutionFailed",
    "ToolExecutionMiddleware",
    "ToolExecutionStarted",
    "ToolResultReady",
    "ToolsReducer",
    "TurnResolveContext",
    "TurnSpec",
    "TurnState",
    "UserQueryReceived",
]
