"""Публичный API агент-слоя.

Реэкспортирует ошибки, события, сообщения, модели, prompt-примитивы и
middleware-цепочку (см. :mod:`boba.domain.agent.meat`).

Короткие импорты::

    from boba.domain.agent import Agent, AgentConfig, AgentContext
    from boba.domain.agent import AgentEvent, AnswerComplete, ToolResultReady

Имена событий ``LLMUserPromptIssued``, ``LLMRequestStarted``,
``LLMRequestSent`` принадлежат agent-слою и отличаются от одноимённых
событий из :mod:`boba.domain.llm.events` — не смешивать.
"""

from boba.domain.agent.errors import (
    LLMToolCallFormatError,
    MaxIterationsExceededError,
    RepeatedFormatFailureError,
    ToolFeedbackError,
)
from boba.domain.agent.events import (
    AgentEvent,
    AgentEventName,
    AnswerComplete,
    AnswerDiscarded,
    AnswerStarted,
    AnswerToken,
    BaseAgentEvent,
    DurableMessage,
    GenerationDone,
    GenerationFailed,
    GenerationRetried,
    GenerationStarted,
    GenericTerminalFailure,
    IterationStarted,
    LifecycleMarker,
    LLMRequestSent,
    LLMRequestStarted,
    LLMUserPromptIssued,
    MaxIterationsReached,
    PersistenceFailed,
    PromptFailed,
    RefusalComplete,
    RefusalToken,
    RepeatedFormatFailure,
    StreamingDelta,
    SystemPromptProcessed,
    SystemPromptProcessingStarted,
    TerminalFailure,
    ThinkingComplete,
    ThinkingStarted,
    ThinkingToken,
    ToolCallArgumentDelta,
    ToolCallBegin,
    ToolCallComplete,
    ToolCallFormatFailed,
    ToolExecutionFailed,
    ToolExecutionStarted,
    ToolResultReady,
    UserNotification,
    UserPromptProcessed,
    UserPromptProcessingStarted,
    UserQueryReceived,
)
from boba.domain.agent.meat import (
    Agent,
    AgentErrorRouter,
    AgentErrorRouterMiddleware,
    AssistantMessagePersistenceMiddleware,
    HistoryMiddleware,
    IterationCounterMiddleware,
    JsonContentToolCallMiddleware,
    JsonDepthScanner,
    JsonHeaderParser,
    JsonToolCallHeader,
    LLMEventToAgentEventConverter,
    LLMInvokeMiddleware,
    NewLLMRequestMiddleware,
    ParsedJsonToolCall,
    RepeatedFormatFailureGuardMiddleware,
    RepeatedToolCallGuardMiddleware,
    SamplingMiddleware,
    StopOnAnyFailure,
    StopOnFinished,
    StrictJsonContentToolCallMiddleware,
    StrictJsonToolCallParser,
    SystemPromptMiddleware,
    ToolExecutionMiddleware,
    ToolsDefinitionMiddleware,
    UserPromptMiddleware,
)
from boba.domain.agent.messages import (
    MessageService,
    MessageStoreError,
    MessageStoreReadError,
    MessageStoreWriteError,
)
from boba.domain.agent.models import AgentConfig, AgentContext, AgentRequest
from boba.domain.agent.prompt import (
    PermanentPromptError,
    PromptBlock,
    PromptError,
    PromptFactory,
    PromptId,
    PromptKind,
    PromptProvider,
    PromptProviderError,
    PromptResult,
    PromptState,
    RetryablePromptError,
)

__all__ = [
    "Agent",
    "AgentConfig",
    "AgentContext",
    "AgentErrorRouter",
    "AgentErrorRouterMiddleware",
    "AgentEvent",
    "AgentEventName",
    "AgentRequest",
    "AnswerComplete",
    "AnswerDiscarded",
    "AnswerStarted",
    "AnswerToken",
    "AssistantMessagePersistenceMiddleware",
    "BaseAgentEvent",
    "DurableMessage",
    "GenerationDone",
    "GenerationFailed",
    "GenerationRetried",
    "GenerationStarted",
    "GenericTerminalFailure",
    "HistoryMiddleware",
    "IterationCounterMiddleware",
    "IterationStarted",
    "JsonContentToolCallMiddleware",
    "JsonDepthScanner",
    "JsonHeaderParser",
    "JsonToolCallHeader",
    "LLMEventToAgentEventConverter",
    "LLMInvokeMiddleware",
    "LLMRequestSent",
    "LLMRequestStarted",
    "LLMToolCallFormatError",
    "LLMUserPromptIssued",
    "LifecycleMarker",
    "MaxIterationsExceededError",
    "MaxIterationsReached",
    "MessageService",
    "MessageStoreError",
    "MessageStoreReadError",
    "MessageStoreWriteError",
    "NewLLMRequestMiddleware",
    "ParsedJsonToolCall",
    "PermanentPromptError",
    "PersistenceFailed",
    "PromptBlock",
    "PromptError",
    "PromptFactory",
    "PromptFailed",
    "PromptId",
    "PromptKind",
    "PromptProvider",
    "PromptProviderError",
    "PromptResult",
    "PromptState",
    "RefusalComplete",
    "RefusalToken",
    "RepeatedFormatFailure",
    "RepeatedFormatFailureError",
    "RepeatedFormatFailureGuardMiddleware",
    "RepeatedToolCallGuardMiddleware",
    "RetryablePromptError",
    "SamplingMiddleware",
    "StopOnAnyFailure",
    "StopOnFinished",
    "StreamingDelta",
    "StrictJsonContentToolCallMiddleware",
    "StrictJsonToolCallParser",
    "SystemPromptMiddleware",
    "SystemPromptProcessed",
    "SystemPromptProcessingStarted",
    "TerminalFailure",
    "ThinkingComplete",
    "ThinkingStarted",
    "ThinkingToken",
    "ToolCallArgumentDelta",
    "ToolCallBegin",
    "ToolCallComplete",
    "ToolCallFormatFailed",
    "ToolExecutionFailed",
    "ToolExecutionMiddleware",
    "ToolExecutionStarted",
    "ToolFeedbackError",
    "ToolResultReady",
    "ToolsDefinitionMiddleware",
    "UserNotification",
    "UserPromptMiddleware",
    "UserPromptProcessed",
    "UserPromptProcessingStarted",
    "UserQueryReceived",
]
