"""Домен каталога данных: процесс (сущности, снимок, операции, diff),
снимки подключений в родной структуре, их diff и кадры синхронизации.
Без I/O."""

from boba.catalog.diff import CatalogDiff, ChangeStatus, DiffEntry
from boba.catalog.model import (
    CatalogEntity,
    CatalogError,
    CatalogInvariantError,
    CatalogModel,
    CatalogSnapshot,
    ColumnLink,
    EntityKind,
    EntityRef,
    Flow,
    FlowEnd,
    Group,
    Node,
    ObjectResolver,
    Position,
)
from boba.catalog.ops import (
    AcceptAll,
    AddFlow,
    AddGroup,
    AddNode,
    CatalogOp,
    CatalogOpBase,
    CatalogOpError,
    CatalogOpKind,
    OperationList,
    RemoveFlow,
    RemoveGroup,
    RemoveNode,
    RetargetNode,
    SetFlow,
    SetGroup,
    SetNode,
)
from boba.catalog.resolver import (
    SnapshotResolver,
)
from boba.catalog.source_diff import (
    FieldChange,
    ObjectChange,
    PartChange,
    SourceDiff,
)
from boba.catalog.sources import (
    Keyed,
    NameList,
    NodeColumn,
    ObjectCard,
    ObjectFamily,
    ObjectKind,
    ObjectRef,
    PartKind,
    PartScope,
    Records,
    SnapshotPart,
    SourceKinds,
    SourceKindsError,
    SourceObject,
    SourceRecord,
    SourceSnapshot,
    SubPart,
    TreeKind,
    TreeNode,
    TreeScope,
)
from boba.catalog.staleness import PinnedSnapshot, Stale, Staleness, StaleReason

__all__ = [
    "AcceptAll",
    "AddFlow",
    "AddGroup",
    "AddNode",
    "CatalogDiff",
    "CatalogEntity",
    "CatalogError",
    "CatalogInvariantError",
    "CatalogModel",
    "CatalogOp",
    "CatalogOpBase",
    "CatalogOpError",
    "CatalogOpKind",
    "CatalogSnapshot",
    "ChangeStatus",
    "ColumnLink",
    "DiffEntry",
    "EntityKind",
    "EntityRef",
    "FieldChange",
    "Flow",
    "FlowEnd",
    "Group",
    "Keyed",
    "NameList",
    "Node",
    "NodeColumn",
    "ObjectCard",
    "ObjectChange",
    "ObjectFamily",
    "ObjectKind",
    "ObjectRef",
    "ObjectResolver",
    "OperationList",
    "PartChange",
    "PartKind",
    "PartScope",
    "PinnedSnapshot",
    "Position",
    "Records",
    "RemoveFlow",
    "RemoveGroup",
    "RemoveNode",
    "RetargetNode",
    "SetFlow",
    "SetGroup",
    "SetNode",
    "SnapshotPart",
    "SnapshotResolver",
    "SourceDiff",
    "SourceKinds",
    "SourceKindsError",
    "SourceObject",
    "SourceRecord",
    "SourceSnapshot",
    "Stale",
    "StaleReason",
    "Staleness",
    "SubPart",
    "TreeKind",
    "TreeNode",
    "TreeScope",
]
